image_generation:
  no_base_image:
    bool: False
    path_to_vocabulary: ""
    path_to_fonts_and_weights_json: ""
    pad_image:
      bool: False
      x_pad: 
      y_pad: 
  base_image:
    bool: True
    path_to_base_image: "handwriting_data_generator/tutorial/resources/007646218_00102_blank_template.png"
    path_to_fonts_and_weights_json: "handwriting_data_generator/tutorial/resources/fonts_and_weights_handwriting_for_iowa_2_float.json" # "sandbox/vocabularies_of_interest/fonts_and_weights.json" #
    partial_base_image: # Will the generated image be words on the full record or clip the record to certain parts
      bool: True
      view_window_path: "handwriting_data_generator/tutorial/resources/occupation_view_window.json"
      fields_to_input_into_format_string: ["occupation"]
      format_string_path: "handwriting_data_generator/tutorial/resources/format_string.txt"
      x_start_left_range_percentage: 0.02
      x_start_right_range_percentage: 0.02
      x_end_left_range_percentage: 0.01
      x_end_right_range_percentage: 0.02
      y_start_lower_range_percentage: 0.05
      y_start_higher_range_percentage: 0.05
      y_end_lower_range_percentage: 0.05
      y_end_higher_range_percentage: 0.05
    fields:
      occupation:
        path_to_quadrilateral: "handwriting_data_generator/tutorial/resources/occupation_text_window.json"
        path_to_vocabulary: "sandbox/vocabularies_of_interest/occupations_representative.json" # "handwriting_data_generator/tutorial/resources/occupations_vocabulary.json" #
        x_start_left_range_percentage: 0.05
        x_start_right_range_percentage: 0.1
        x_end_left_range_percentage: 0.20
        x_end_right_range_percentage: 0.0
        y_start_lower_range_percentage: 0.25
        y_start_higher_range_percentage: 0.15
        y_end_lower_range_percentage: 0.05
        y_end_higher_range_percentage: 0.05
        new_width_random_range_start: 1.5
        new_width_random_range_end: 2.2
        bezier_dash:
          height_range: [45, 45]
          width_range: [100, 300]
          x0_range: [0.0, 0.1]
          x1_range: [0.0, 1.0]
          x2_range: [0.0, 1.0]
          x3_range: [0.9, 1.0]
          y0_range: [0.0, 1.0]
          y1_range: [0.0, 1.0]
          y2_range: [0.0, 1.0]
          y3_range: [0.0, 1.0]
      town_or_township:
        path_to_quadrilateral: "handwriting_data_generator/tutorial/resources/town_or_township_text_window.json"
        path_to_vocabulary: "handwriting_data_generator/tutorial/resources/town_or_township_vocabulary.json"
        x_start_left_range_percentage: 0.0
        x_start_right_range_percentage: 0.1
        x_end_left_range_percentage: 0.33
        x_end_right_range_percentage: 0.0
        y_start_lower_range_percentage: 0.05
        y_start_higher_range_percentage: 0.05
        y_end_lower_range_percentage: 0.05
        y_end_higher_range_percentage: 0.05
        new_width_random_range_start: 0.9
        new_width_random_range_end: 1.1
        bezier_dash:
          height_range: [45, 45]
          width_range: [200, 400]
          x0_range: [0.0, 0.1]
          x1_range: [0.0, 1.0]
          x2_range: [0.0, 1.0]
          x3_range: [0.9, 1.0]
          y0_range: [0.0, 1.0]
          y1_range: [0.0, 1.0]
          y2_range: [0.0, 1.0]
          y3_range: [0.0, 1.0]
      total_earnings:
        path_to_quadrilateral: "handwriting_data_generator/tutorial/resources/earnings_text_window.json"
        path_to_vocabulary: "handwriting_data_generator/tutorial/resources/earnings_vocabulary.json"
        x_start_left_range_percentage: 0.0
        x_start_right_range_percentage: 0.1
        x_end_left_range_percentage: 0.33
        x_end_right_range_percentage: 0.0
        y_start_lower_range_percentage: 0.05
        y_start_higher_range_percentage: 0.05
        y_end_lower_range_percentage: 0.05
        y_end_higher_range_percentage: 0.05
        new_width_random_range_start: 0.9
        new_width_random_range_end: 1.1
        bezier_dash:
          height_range: [45, 45]
          width_range: [200, 400]
          x0_range: [0.0, 0.1]
          x1_range: [0.0, 1.0]
          x2_range: [0.0, 1.0]
          x3_range: [0.9, 1.0]
          y0_range: [0.0, 1.0]
          y1_range: [0.0, 1.0]
          y2_range: [0.0, 1.0]
          y3_range: [0.0, 1.0]

background_color: 
  uniform:
    bool: False
    lower_bound: 255
    upper_bound: 255
  gaussian:
    bool: False
    mean: 200
    standard_deviation: 25
    clip_values_at_number_of_std_deviations: 2
  static:
    bool: True
    value: 255

draw_underlines:
  draw_full_underline_frequency: 0.25
  draw_dotted_underlines_frequency: 0.5
  draw_no_underline_frequency: 0.25

underline_color:
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
  gaussian:
    bool: True
    mean: 20
    standard_deviation: 10
    clip_values_at_number_of_std_deviations: 1
  static:
    bool: False
    value: 120

font_size:
  static:
    bool: True
    value: 80
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
    within_and_across_images: True
    across_images_only: False
  gaussian: 
    bool: False
    mean: 50
    standard_deviation: 2
    clip_values_at_number_of_std_deviations: 1
    within_and_across_images: True
    across_images_only: False

font_color:
  within_and_across_images: True
  across_images_only: False
  same_for_all_images: False
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
  gaussian: 
    bool: True
    mean: 40
    standard_deviation: 30
    clip_values_at_number_of_std_deviations: 1.0
  static:
    bool: False
    value: 120