path_to_vocabulary: ''
path_to_fonts_and_weights_json: ''

fonts:
  different_fonts_per_word: False

size_images_differently:
  bool: True
  vertical_proportional_bounds: 2
  horizontal_proportional_bounds: 2

image_padding:
  pad_left: 3
  pad_top: 3
  pad_right: 3
  pad_bottom: 3

image_sizing:
  static:
    bool: False
    pad_left: 1.05
    pad_top: 2.0
    pad_right: 2.0
    pad_bottom: 1.05
  uniform:
    bool: True
    vertical_resize_multiplier: 2
    horizontal_resize_multiplier: 3
  gaussian:
    bool: False 
    mean: 0.5
    standard_deviation: 0.16
    clip_values_at_number_of_std_deviations: 3 
  pareto:
    bool: False 
    alpha: 2.5

font_size:
  static:
    bool: False
    value: 12
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
    within_and_across_images: True
    across_images_only: False
  gaussian: 
    bool: True
    mean: 50
    standard_deviation: 2
    clip_values_at_number_of_std_deviations: 1
    within_and_across_images: True
    across_images_only: False
  
crop_top_and_bottom_of_words_ratio: .02

background_color: 
  uniform:
    bool: False
    lower_bound: 225
    upper_bound: 255
  gaussian:
    bool: True
    mean: 200
    standard_deviation: 25
    clip_values_at_number_of_std_deviations: 2
  static:
    bool: False
    value: 120

font_color:
  within_and_across_images: True
  across_images_only: False
  same_for_all_images: False
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
  gaussian: 
    bool: True
    mean: 20
    standard_deviation: 10
    clip_values_at_number_of_std_deviations: 1
  static:
    bool: False
    value: 120

draw_underlines:
  draw_full_underline_frequency: 0.25
  draw_dotted_underlines_frequency: 0.5
  draw_no_underline_frequency: 0.25

underline_color:
  within_and_across_images: True
  across_images_only: False
  same_for_all_images: False
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
  gaussian: 
    bool: True
    mean: 20
    standard_deviation: 10
    clip_values_at_number_of_std_deviations: 1
  static:
    bool: False
    value: 120

image_maker_parameters:
  image_width_multiplier: 1.4
  image_height_multiplier: 1.7
  start_text_x_fraction_of_width: 0.1
  start_text_y_fraction_of_height: 0.1