path_to_vocabulary: "RLL_handwriting_data_generator/vocabularies_of_interest/vocabularies_2.json"
path_to_fonts_and_weights_json: "RLL_handwriting_data_generator/vocabularies_of_interest/fonts_and_weights.json"

font_size:
  static:
    bool: True
    value: 80
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
    within_and_across_images: True
    across_images_only: False
  gaussian: 
    bool: False
    mean: 50
    standard_deviation: 2
    clip_values_at_number_of_std_deviations: 1
    within_and_across_images: True
    across_images_only: False
  
background_color: 
  uniform:
    bool: False
    lower_bound: 225
    upper_bound: 255
  gaussian:
    bool: False
    mean: 200
    standard_deviation: 25
    clip_values_at_number_of_std_deviations: 2
  static:
    bool: True
    value: 255

font_color:
  within_and_across_images: True
  across_images_only: False
  same_for_all_images: False
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
  gaussian: 
    bool: True
    mean: 50
    standard_deviation: 10
    clip_values_at_number_of_std_deviations: 1
  static:
    bool: False
    value: 120

draw_underlines:
  draw_full_underline_frequency: 0.25
  draw_dotted_underlines_frequency: 0.5
  draw_no_underline_frequency: 0.25

underline_color:
  within_and_across_images: True
  across_images_only: False
  same_for_all_images: False
  uniform: 
    bool: False
    lower_bound: None
    upper_bound: None
  gaussian: 
    bool: True
    mean: 20
    standard_deviation: 10
    clip_values_at_number_of_std_deviations: 1
  static:
    bool: False
    value: 120

pad_image:
  y_pad: 2.0
  x_pad: 2.0